package com.medical.manager.product.web.model;

public class TblExpress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_express.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_express.EXPRESS_NAME
     *
     * @mbggenerated
     */
    private String expressName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_express.ID
     *
     * @return the value of tbl_express.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_express.ID
     *
     * @param id the value for tbl_express.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_express.EXPRESS_NAME
     *
     * @return the value of tbl_express.EXPRESS_NAME
     *
     * @mbggenerated
     */
    public String getExpressName() {
        return expressName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_express.EXPRESS_NAME
     *
     * @param expressName the value for tbl_express.EXPRESS_NAME
     *
     * @mbggenerated
     */
    public void setExpressName(String expressName) {
        this.expressName = expressName == null ? null : expressName.trim();
    }
}