package com.medical.manager.product.web.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.medical.manager.product.web.model.TblExpress;
import com.medical.manager.product.web.query.TblExpressExample;

@Repository("tblExpressDao")
public interface ITblExpressDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_express
     *
     * @mbggenerated
     */
    int countByExample(TblExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_express
     *
     * @mbggenerated
     */
    int deleteByExample(TblExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_express
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_express
     *
     * @mbggenerated
     */
    int insert(TblExpress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_express
     *
     * @mbggenerated
     */
    int insertSelective(TblExpress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_express
     *
     * @mbggenerated
     */
    List<TblExpress> selectByExample(TblExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_express
     *
     * @mbggenerated
     */
    TblExpress selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_express
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblExpress record, @Param("example") TblExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_express
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblExpress record, @Param("example") TblExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_express
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblExpress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_express
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblExpress record);
}