package com.medical.manager.systemset.web.model;

public class TblSysReceivables {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_receivables.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_receivables.ALIPAY_NAME
     *
     * @mbggenerated
     */
    private String alipayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_receivables.ALIPAY_ACCOUNT
     *
     * @mbggenerated
     */
    private String alipayAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_receivables.PUBLIC_ACCOUNT_COMPANY
     *
     * @mbggenerated
     */
    private String publicAccountCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_receivables.PUBLIC_ACCOUNT
     *
     * @mbggenerated
     */
    private String publicAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_receivables.PUBLIC_ACCOUNT_BANK
     *
     * @mbggenerated
     */
    private String publicAccountBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_receivables.PERSON_NAME
     *
     * @mbggenerated
     */
    private String personName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_receivables.PERSON_ACCOUNT
     *
     * @mbggenerated
     */
    private String personAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_receivables.PERSON_ACCOUNT_BANK
     *
     * @mbggenerated
     */
    private String personAccountBank;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_receivables.ID
     *
     * @return the value of tbl_sys_receivables.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_receivables.ID
     *
     * @param id the value for tbl_sys_receivables.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_receivables.ALIPAY_NAME
     *
     * @return the value of tbl_sys_receivables.ALIPAY_NAME
     *
     * @mbggenerated
     */
    public String getAlipayName() {
        return alipayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_receivables.ALIPAY_NAME
     *
     * @param alipayName the value for tbl_sys_receivables.ALIPAY_NAME
     *
     * @mbggenerated
     */
    public void setAlipayName(String alipayName) {
        this.alipayName = alipayName == null ? null : alipayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_receivables.ALIPAY_ACCOUNT
     *
     * @return the value of tbl_sys_receivables.ALIPAY_ACCOUNT
     *
     * @mbggenerated
     */
    public String getAlipayAccount() {
        return alipayAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_receivables.ALIPAY_ACCOUNT
     *
     * @param alipayAccount the value for tbl_sys_receivables.ALIPAY_ACCOUNT
     *
     * @mbggenerated
     */
    public void setAlipayAccount(String alipayAccount) {
        this.alipayAccount = alipayAccount == null ? null : alipayAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_receivables.PUBLIC_ACCOUNT_COMPANY
     *
     * @return the value of tbl_sys_receivables.PUBLIC_ACCOUNT_COMPANY
     *
     * @mbggenerated
     */
    public String getPublicAccountCompany() {
        return publicAccountCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_receivables.PUBLIC_ACCOUNT_COMPANY
     *
     * @param publicAccountCompany the value for tbl_sys_receivables.PUBLIC_ACCOUNT_COMPANY
     *
     * @mbggenerated
     */
    public void setPublicAccountCompany(String publicAccountCompany) {
        this.publicAccountCompany = publicAccountCompany == null ? null : publicAccountCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_receivables.PUBLIC_ACCOUNT
     *
     * @return the value of tbl_sys_receivables.PUBLIC_ACCOUNT
     *
     * @mbggenerated
     */
    public String getPublicAccount() {
        return publicAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_receivables.PUBLIC_ACCOUNT
     *
     * @param publicAccount the value for tbl_sys_receivables.PUBLIC_ACCOUNT
     *
     * @mbggenerated
     */
    public void setPublicAccount(String publicAccount) {
        this.publicAccount = publicAccount == null ? null : publicAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_receivables.PUBLIC_ACCOUNT_BANK
     *
     * @return the value of tbl_sys_receivables.PUBLIC_ACCOUNT_BANK
     *
     * @mbggenerated
     */
    public String getPublicAccountBank() {
        return publicAccountBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_receivables.PUBLIC_ACCOUNT_BANK
     *
     * @param publicAccountBank the value for tbl_sys_receivables.PUBLIC_ACCOUNT_BANK
     *
     * @mbggenerated
     */
    public void setPublicAccountBank(String publicAccountBank) {
        this.publicAccountBank = publicAccountBank == null ? null : publicAccountBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_receivables.PERSON_NAME
     *
     * @return the value of tbl_sys_receivables.PERSON_NAME
     *
     * @mbggenerated
     */
    public String getPersonName() {
        return personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_receivables.PERSON_NAME
     *
     * @param personName the value for tbl_sys_receivables.PERSON_NAME
     *
     * @mbggenerated
     */
    public void setPersonName(String personName) {
        this.personName = personName == null ? null : personName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_receivables.PERSON_ACCOUNT
     *
     * @return the value of tbl_sys_receivables.PERSON_ACCOUNT
     *
     * @mbggenerated
     */
    public String getPersonAccount() {
        return personAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_receivables.PERSON_ACCOUNT
     *
     * @param personAccount the value for tbl_sys_receivables.PERSON_ACCOUNT
     *
     * @mbggenerated
     */
    public void setPersonAccount(String personAccount) {
        this.personAccount = personAccount == null ? null : personAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_receivables.PERSON_ACCOUNT_BANK
     *
     * @return the value of tbl_sys_receivables.PERSON_ACCOUNT_BANK
     *
     * @mbggenerated
     */
    public String getPersonAccountBank() {
        return personAccountBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_receivables.PERSON_ACCOUNT_BANK
     *
     * @param personAccountBank the value for tbl_sys_receivables.PERSON_ACCOUNT_BANK
     *
     * @mbggenerated
     */
    public void setPersonAccountBank(String personAccountBank) {
        this.personAccountBank = personAccountBank == null ? null : personAccountBank.trim();
    }
}