package com.medical.manager.systemset.web.model;

public class TblSysInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_info.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_info.PARAM_NAME
     *
     * @mbggenerated
     */
    private String paramName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_info.PARAM_TYLE
     *
     * @mbggenerated
     */
    private String paramTyle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_info.PARAM_VALUE
     *
     * @mbggenerated
     */
    private String paramValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_info.RECHARGE
     *
     * @mbggenerated
     */
    private String recharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_info.FREE
     *
     * @mbggenerated
     */
    private String free;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_info.ID
     *
     * @return the value of tbl_sys_info.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_info.ID
     *
     * @param id the value for tbl_sys_info.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_info.PARAM_NAME
     *
     * @return the value of tbl_sys_info.PARAM_NAME
     *
     * @mbggenerated
     */
    public String getParamName() {
        return paramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_info.PARAM_NAME
     *
     * @param paramName the value for tbl_sys_info.PARAM_NAME
     *
     * @mbggenerated
     */
    public void setParamName(String paramName) {
        this.paramName = paramName == null ? null : paramName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_info.PARAM_TYLE
     *
     * @return the value of tbl_sys_info.PARAM_TYLE
     *
     * @mbggenerated
     */
    public String getParamTyle() {
        return paramTyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_info.PARAM_TYLE
     *
     * @param paramTyle the value for tbl_sys_info.PARAM_TYLE
     *
     * @mbggenerated
     */
    public void setParamTyle(String paramTyle) {
        this.paramTyle = paramTyle == null ? null : paramTyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_info.PARAM_VALUE
     *
     * @return the value of tbl_sys_info.PARAM_VALUE
     *
     * @mbggenerated
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_info.PARAM_VALUE
     *
     * @param paramValue the value for tbl_sys_info.PARAM_VALUE
     *
     * @mbggenerated
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue == null ? null : paramValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_info.RECHARGE
     *
     * @return the value of tbl_sys_info.RECHARGE
     *
     * @mbggenerated
     */
    public String getRecharge() {
        return recharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_info.RECHARGE
     *
     * @param recharge the value for tbl_sys_info.RECHARGE
     *
     * @mbggenerated
     */
    public void setRecharge(String recharge) {
        this.recharge = recharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_info.FREE
     *
     * @return the value of tbl_sys_info.FREE
     *
     * @mbggenerated
     */
    public String getFree() {
        return free;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_info.FREE
     *
     * @param free the value for tbl_sys_info.FREE
     *
     * @mbggenerated
     */
    public void setFree(String free) {
        this.free = free;
    }
}